blank_issues_enabled: true
contact_links:
  - name: AndaluzCoin Core Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: AndaluzCoin Core Developers
    url: https://bitcoincore.org
    about: AndaluzCoin Core homepage
