blank_issues_enabled: true
contact_links:
  - name: Andaluzcoin Core Security Policy
    url: https://github.com/andaluzcoin/andaluzcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Andaluzcoin Core Developers
    url: https://andaluzcoincore.org
    about: Andaluzcoin Core homepage
